In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [5]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [6]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [7]:
a * b

array([2., 4., 6., 8.])

In [8]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [9]:
a = np.arange(10000)
%timeit a + 1 

14.5 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
l = range(10000)
%timeit [i+1 for i in l] 

1.52 ms ± 32.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
c = np.ones((3, 3))
c * c   

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [100]:
#Exercise: Elementwise operations

#Try simple arithmetic elementwise operations: add even elements with odd elements
#Time them against their pure python counterparts using %timeit.
#Generate:
#[2**0, 2**1, 2**2, 2**3, 2**4]
#a_j = 2^(3*j) - j

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a,b)

False

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a,c)

True

In [16]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [17]:
np.logical_and(a, b)

array([ True, False, False, False])

In [18]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
np.log(a)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [20]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [21]:
a = np.arange(4)
a + np.array([1, 2])  

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [22]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [101]:
#Exercise other operations

#Look at the help for np.allclose. When might this be useful?
#Look at the help for np.triu and np.tril.

In [24]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [25]:
x.sum()

10

In [26]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [27]:
x.sum(axis=0)

array([3, 3])

In [28]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [29]:
x.sum(axis=1) 

array([2, 4])

In [30]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [32]:
x =np.random.rand(2, 2,2)
x.sum(axis =2) [0,1]

0.2539604602398038

In [33]:
x[0,1 :].sum()

0.2539604602398038

In [34]:
x = np.array([1, 3, 2])
x.min()

1

In [35]:
x.max()

3

In [36]:
x.argmin()  

0

In [37]:
x.argmax()

1

In [38]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [39]:
np.all(a == a)

True

In [40]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [41]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [42]:
np.median(x)

1.5

In [43]:
np.median(y, axis=-1) 

array([2., 5.])

In [44]:
x.std() 

0.82915619758885

In [102]:
#Exercise: Reductions

#Given there is a sum, what other function might you expect to see?
#What is the difference between sum and cumsum?

In [52]:
#Worked Example: data statistics

#Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

!cat data/populations.txt

data = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = data.T

from matplotlib import pyplot as plt
plt.axes([0.2, 0.1, 0.5, 0.8]) 
plt.plot(year, hares, year, lynxes, year, carrots) 
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5)) 

populations = data[:, 1:]
populations.mean(axis=0)

'cat' is not recognized as an internal or external command,
operable program or batch file.


OSError: data/populations.txt not found.

In [103]:
#Worked Example: diffusion using a random walk algorithm

In [61]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [62]:
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [63]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 1
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [65]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

In [66]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [67]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [68]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,
       1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [69]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

In [72]:
plt.pcolor(distance)    
plt.colorbar() 

#MASIH ERRORRRR

NameError: name 'plt' is not defined

In [73]:
x, y = np.ogrid[0:5, 0:5]
x, y
x.shape, y.shape

((5, 1), (1, 5))

In [74]:
x,y = np.mgrid[0:4, 0:4]
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [75]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [76]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [77]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [79]:
a.shape

(2, 3)

In [80]:
b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
a.reshape((2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
b[0,0] = 99
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [83]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] =9
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [85]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [86]:
z[np.newaxis, :]

array([[1, 2, 3]])

In [87]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [88]:
a[0, 2, 1]


5

In [89]:
b = a.transpose(1, 2, 0)
b.shape

(3, 2, 4)

In [90]:
b[2, 1, 0]

5

In [91]:
b[2, 1, 0] = -1
a[0, 2, 1]

-1

In [92]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [93]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
#Exercise: Shape manipulations

#Look at the docstring for reshape, especially the notes section which has some more information about copies and views.
#Use flatten as an alternative to ravel. What is the difference? (Hint: check which one returns a view and which a copy)
#Experiment with transpose for dimension shuffling.

In [94]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [95]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

In [96]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [97]:
a[j]

array([1, 2, 3, 4])

In [98]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min


(0, 2)

In [104]:
#Exercise: Sorting

#Try both in-place and out-of-place sorting.
#Try creating arrays with different dtypes and sorting them.
#Use all or array_equal to check the results.
#Look at np.random.shuffle for a way to create sortable input quicker.
#Combine ravel, sort and reshape.
#Look at the axis keyword for sort and rewrite the previous exercise.